add partner_area and web_google_maps_drawing for Odoo13
gityopie/odoo-addons pull request #153
Opened 2021-02-04 16:30 UTC by crece365

2021-02-06 16:32 UTC, gityopie requested changes
Hi @crece365 
Several points to check on your side :)

Thanks for the PR!

2021-02-06 16:32 UTC, gityopie commented on web_google_maps_drawing/__manifest__.py
> +    'version': '12.0.1.0.0',
Could you please update the version number?

2021-02-06 16:32 UTC, gityopie commented on web_google_maps_drawing/data/google_maps_library.xml
> +        <function model="ir.config_parameter" name="set_param" eval="('google.maps_libraries', 'geometry,places,drawing')"/>
The config param `key` should be `web_google_maps.maps_libraries`

2021-02-06 16:32 UTC, gityopie commented on web_google_maps_drawing/example/partner_area/__manifest__.py
> +    'version': '12.0.1.0.1',
same for the version number :)

2021-02-06 16:32 UTC, gityopie commented on partner_area/views/res_partner.xml
> +                        <map library="drawing" string="Shape">
The view `map` has been changed to `google_map`. On the enterprise, Odoo has this view type

2021-02-06 16:32 UTC, gityopie commented on partner_area/views/res_partner_area.xml
> +    <!--record model="ir.ui.view" id="view_res_partner_area_kanban">
If this view is no longer necessary, please remove it :)

2021-02-06 16:32 UTC, gityopie commented on web_google_maps_drawing/example/partner_area/views/res_partner.xml
> +                        <map library="drawing" string="Shape">
should be `google_map` not `map` 
and the other views that still using `map`

2021-06-01 06:33 UTC, macagua commented
@crece365 please, check out the @gityopie review and make these changes!!!

2021-09-07 13:58 UTC, closed without merging